[tool.poetry]
name = "savedit"
version = "0.1.0"
description = "Send saved Reddit posts to other services"
authors = ["Kevin Lane <lane.kevin.a@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
